export const categoriesOfArchitects = [
    {value: 'all', label: 'All'},
    {value: 'residential', label: 'Residential'},
    {value: 'interiors', label: 'Interiors'},
    {value: 'commercial', label: 'Commercial'},
    {value: 'healthcare', label: 'Healthcare'},
    {value: 'housing', label: 'Housing'},
    {value: 'institutional', label: 'Institutional'},
    {value: 'competitions', label: 'Competitions'},
    {value: 'hospitality', label: 'Hospitality'},

]

export const architects = [
    {
        id: 1,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'residential',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
    {
        id: 2,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa2',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'interiors',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
    {
        id: 3,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa3',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'commercial',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
    {
        id: 4,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa4',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'healthcare',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
    {
        id: 5,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa5',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'housing',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
    {
        id: 6,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa6',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'institutional',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
    {
        id: 7,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa7',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'competitions',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
    {
        id: 8,
        fullName: 'Kowdiar Villa',
        slug: 'kowdiar-villa8',
        description: 'The conventional courtyard house is conceived around an open space (garden). Typically the courtyard has a distinct character which is homogenous. Questioning this cliché the idea was to articulate a new experience in the courtyard by having a large garden and a large water body in it. The juxtaposition of the water body and the garden along with central spine of the house helps organize the rest of the program. The central void segments the public and the private zones of the house at the ground level. The central spine which connects the garden and the pool in one axis and the public and private in the other axis is envisioned to transform into a quasi-art gallery over time.  The central spine at the upper level accommodates a library and connects the bedrooms on either side of the courtyard. All the spaces flanking the courtyard have a deep porous edge in the form of balconies to negotiate the transition from outside to inside. These deep balconies also help cut the glare and the heat to insulate the interiors better.',
        category: 'hospitality',
        location: 'Trivandrum , Kerala',
        year: [2015, 2018],
        status: 'Completed',
        area: '30,000 SQFT',
        client: 'Pothys',
        Architects: ['Rejin Karthik', 'Nirali Ashra', 'Smaran Mallesh', 'Vikram Rajashekar', 'Narendra Pirgal'],
        images: ['https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/Kowdiar-cover-scaled.jpg?fit=1368%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8687-scaled.jpg?fit=608%2C912&ssl=1', 'https://i0.wp.com/cadencearchitects.com/wp-content/uploads/2021/06/IMG_8628.jpg?fit=879%2C586&ssl=1'],
        imageAlt: 'Kowdiar Villa'
    },
]